### ISSUE TITLE
Implicit monads and concatenable types

### ISSUE THREAD

**Issue by ericvanwyk** [melt-umn/silver#425] opened 2021-01-09 22:53 UTC
The definition of `x.msg` in the grammar below generates an error from the Silver-Silver expressions in `Expr.sv` in the implicit monads extension. That error is:
```
Expr.sv:2100:13: error: a is not a concatenable type.
```

The problem seems to be with the `case` expression.  If that is replaced by a string literal then it works.

This is the grammar the demonstrates this error.
```
grammar test;

function main
IOVal<Integer> ::= args::[String] io_in::IO
{
  local x :: X = mk_X (mk_Y ("hello ") );
  local s :: String = case x.msg of
                      | right(msg) -> msg
                      | left (err) -> err
                      end;
  return ioval (print (s ++ "\n", io_in) , 0);
}

implicit synthesized attribute msg :: Either<String String>;
attribute msg occurs on X, Y;

nonterminal X;
production mk_X
x::X ::= y::Y
{ x.msg = y.msg ++ 
          case just("h") of
          | just(s) -> s
          | nothing() -> "Oh no!"
          end;
}

nonterminal Y;
production mk_Y
y::Y ::= s::String
{ y.msg = s;
}
```

Unless I'm doing something daft this seems to be a problem.

The error message is also not very helpful since it doesn't tell one where this `Expr.sv` file is - we have several. Perhaps the thinking is that this error is for the extension writer and they will know where to look.

**Comment by RandomActsOfGrammar** [comment] 2021-01-12 22:20
There are two issues here:
1. This code should work, but doesn't.
2. The error message shows an unhelpful location.

### Issue 1:
I think the error causing the code to fail is an existing bug which the translation just shows.  If I fix issue 2 for this particular case, we get an error from `javac` instead of Silver, but they appear to be related to the same root cause of generated type variables coming from the translation.

Consider the following nonsensical production:
```
concrete production testForwarding
top::Expr ::= '&AOEU' e::Expr '&AOEU'
{
  -- (\ x::a -> x) e
  local fwd::Expr =
        buildApplication(buildLambda("x", freshType(),
                                     buildName("x", top.location), top.location),
                         [e], top.location);
  forwards to fwd;
}
```
Using some helper functions which do exactly what their names suggest, this forwards to applying a lambda, which is the identity function, to whatever expression the construct was given.  This identity function has `freshType()` for the type of the argument.  Suppose we write an equation as follows, where `s` has type `String`:
```
y.xa = &AOEU "aoeu" &AOEU ++ s;
```
This should be fine, and should compile fine.  However, we get the following error from `javac` when we try to do so:
```
[javac] <file>.java:150: error: incompatible types: Object cannot be converted to StringCatter
[javac]      return ((Object)common.Util.demand(lambdaParam_2_x));
```
If we replace `freshType()` in the `testForwarding` production with `stringType()`, it compiles successfully.  I think the issue has something to do with translation to Java without using type substitutions to get the actual type.

### Issue 2:
The error message's strange location is because it uses `Silver_Expr` to do the rewriting.  Then the rewritten append is actual parsed out of the `Expr.sv` file in the `implicit_monads` extension on line `2100`, and we have lost its connection to the original location.  This is the case with errors that should be raised as well, not just bugs in the compiler.

The solution is to stop using antiquote productions on code that isn't thoroughly checked before translation to guarantee there will be no errors.  I can go through and remove them from the `implicit_monads` extension and replace them with building the syntax trees by hand, but I think this is probably an issue that pops up wherever antiquotes are used for a translation, including forwarding, where errors can also be generated on the translated code.

**Comment by krame505** [comment] 2021-01-12 22:27
These issues of source locations showing up in error messages due to the use of antiquotes would be fixed by using origins, if we ever get around to switching over Silver.  

Another potential fix, rather than rewriting all of the antiquoted trees by hand, would be to use term rewriting to update the locations in the rewritten tree.  For example this might look something like 
```
top.monadRewritten = rewriteWith(
  allTopDown(rule on Location of loc(file, _, _ ,_ ,_ ,_ , _) when file != top.location.filename -> top.location end),
  Silver_Expr { ... }).fromJust;
```
Of course this involves reflection and would come with a small performance hit to the Silver compiler when using this feature.

**Comment by RandomActsOfGrammar** [comment] 2021-01-12 23:23
That hack doesn't work in all cases.  Suppose we are writing code in a file named `Expr.sv` for expressions in a new language.  Then we wouldn't replace the location from the extension with the actual location.  For example, if an error comes from line 35 in the new language's `Expr.sv` file and we get an error in `monadRewritten` on line 2100 of `implicit_monads/Expr.sv`, we will show line 2100 still.

I think I will leave the error message locations unhelpful for now, and see what comes of #434.

**Comment by RandomActsOfGrammar** [comment] 2022-01-18 19:28
I decided to look at this again as long as I was knocking out Silver issues, and it looks like this isn't a problem anymore.  The given grammar compiled and ran fine.

**Closed by RandomActsOfGrammar** 2022-01-18 19:28 UTC
Labels: bug
