### ISSUE TITLE
Make Silver use Origin Tracking

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#517] opened 2021-05-04 15:58 UTC
Silver itself should use origin tracking

**Comment by remexre** [comment] 2022-01-12 16:35
As discussed today, this might have issues with preserving locations if origins aren't serialized -- some mechanism for serializing at least the location part is probably necessary, though exactly how much to serialize is probably worth thought and discussion.

**Comment by krame505** [comment] 2022-01-12 16:46
`DclInfo`s that go in the interface files have the `sourceLocation` annotation, that wouldn't change when moving to origins.  
The issue is if we decide to add location info to the CST AST trees, since those go in the environment.  I think the solution to that might just be "use the location annotation and not origins", though - I don't think that would have any significant downsides besides having to manually write the locations (which we need to do anyway until the rest of Silver moves to use origins...)

**Comment by krame505** [comment] 2023-09-16 03:41
Given how (relatively) easy this was in ableC, and how useful this is in error messages and debugging, I would suggest we move ahead with this sooner rather than later.

**Closed** 2023-10-07 01:45 UTC
Labels: wishlist
