### ISSUE TITLE
flatMap

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#123] opened 2017-03-09 17:55 UTC
Should there be a flatMap function in the standard library? It's in [Haskell (named `>>=`)](https://hackage.haskell.org/package/base-4.9.1.0/docs/Prelude.html#v:-62--62--61-), [Rust](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.flat_map), and [Scala](http://www.scala-lang.org/api/current/scala/collection/immutable/List.html#flatMap[B](f:A=>scala.collection.GenTraversableOnce[B]):List[B]); seems like a "expected to be there" function, even if it is a tiny implementation.

```silver
function flatMap
[b] ::= f::([b] ::= a) l::[a]
{
  return foldr(append, [], map(f, l));
}
```

Also, should there be a concat function (`[a] ::= [[a]]`)? That's another thing I "expected to be there," even if it is just `foldr(append, [], l);`.

**Comment by tedinski** [comment] 2017-03-09 20:50
Duplicate of issue #105, though I'll go add a note about concat and the name.

**Closed by tedinski** 2017-03-09 20:50 UTC
Labels: duplicate, enhancement
