### ISSUE TITLE
Can't shadow production names in a case expression.

### ISSUE THREAD

**Issue by remexre** [melt-umn/silver#125] opened 2017-03-21 21:32 UTC
For example, the code

```
case result.parseError of
| syntaxError(_, loc, _, _) -> error("asdfasdf")
| _ -> error("qwerty")
end
```

fails with

`error: Production name can't be used in pattern`

while

```
case result.parseError of
| syntaxError(_, l, _, _) -> error("asdfasdf")
| _ -> error("qwerty")
end
```

succeeds. This is probably because `loc` is the name of a production.

**Comment by tedinski** [comment] 2017-03-21 23:18
Unless you object, I think this should be closed as working as intended.

We had issues with people used to Haskell, e.g., matching against `| nothing -> ...` which binds a pattern variable and doesn't match the production (should be `| nothing() -> ...`). Forbidding production names as patterns was the simplest way to spot this error we could think of.

Kind of an unfortunately result of us not having a clean capitalized-vs-uncapitalized distinction between constructors and variables like Haskell does.

**Comment by remexre** [comment] 2017-03-22 08:20
Would it make more sense to make that a warning instead?
Or to only disallow for zero-argument productions?
Or only productions that are at the "root" of a pattern? (i.e. disallow `| nothing ->`, but not `| foo(nothing) ->`)

**Comment by tedinski** [comment] 2017-03-22 13:23
Warning: It's probably could be. Do you run into this often?

Zero arg: That... might be a good way to mitigate it. Another option I originally considered was limiting it to productions of the appropriate type. But I think what happened was I implemented it as it is now, and ran into so few problems with it I decided it was good enough as-is.

The latter though: no, nested patterns lead to the same issue. What is they meant `foo(nothing())`?

**Comment by remexre** [comment] 2017-03-22 17:05
I only ran into this the one time, but it was extremely non-intuitive:

> `error: Production name can't be used in pattern`
> Whaddya mean? Aren't patterns production names?

An ideal solution for me would be to restrict it to zero-argument productions and to make it a warning.

To avoid getting into the C programmer's habit of "there are 1280 warnings, but no errors, so it must be OK," we might also want to reduce the default verbosity of the compiler somewhat, and possibly make the presence of warnings without some sort of "allow this specific warning here because <x>" annotation a Jenkins failure.

**Comment by tedinski** [comment] 2017-03-22 21:45
Oi, that error message should be fixed, at least.

**Comment by ericvanwyk** [comment] 2017-03-22 23:04
This isn't really an error and doesn't feel like a warning to me.  It seems
more like something that a linter would report.

But we don't have a linter and it is too easy to miss a warning in the
verbose Silver output.  For now I would create a verbose error message that
explains the motivation for it being a error.  In this case, something
like:  "loc" is the name of a production and these names cannot be used as
pattern variables.  The reason for this is that forgetting parenthesis on a
nullary production causes that production name to be parsed as a pattern
variable, a not too uncommon error.   Or something like that - but maybe
less verbose.

**Comment by remexre** [comment] 2017-03-22 23:35
Also, we might want to reduce the amount of output Silver produces without a verbose flag, perhaps.

**Comment by ericvanwyk** [comment] 2017-03-22 23:44
I would like it if Silver was less verbose.  Some of the testing scripts in
demo extensions indicate what to go looking for to detect a certain
problem.  It would be nice if Silver said nothing if it all worked.

**Closed** 2017-04-27 00:06 UTC
Labels: BadErrorMessage
